config/routes.rb
Rails.application.routes.draw do
  root 'videos#index'
  resources :videos
  get '/videos/:id/like' => 'videos#like'
  get '/videos/:id/dislike' => 'videos#dislike'
  devise_for :users
  resources :users

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # assoc
  has_many :videos
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/video.rb
class Video < ApplicationRecord
  #association
  belongs_to :user
  def like!
	  self.likes += 1
	  save
  end
  def dislike!
	  self.likes -= 1
	  save
  end
	 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  protect_from_forgery with: :exception
  layout :layout_by_resource
  protected
  def layout_by_resource
	  if devise_controller?
		  'devise'
	  else
		  'application'
	  end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # Checks if user is signed in before running controller, functionality provided by devise
  before_action :set_user, only: [:show]
  before_action :set_current_user, only: [:edit, :update]
  def index
    @users = User.all
  end
  def show
    @user = User.find(params[:id])
    authorize @user
  end
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private
  def set_user
    @user = User.find(params[:id])
  end
  def set_current_user
    @user = current_user
  end
  def user_params
    params.require(:user).permit(:email)
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_video, only: [:show, :edit, :like, :dislike]
  # All published videos
  def index
	  @videos = Video.all
  end
  def show
    @videos = Video.find(params[:id])
    Rails.logger.debug("video show #{@videos.attributes.inspect}")
  end
  def new
    Rails.logger.debug("video new")
    @video = Video.new
  end
  def edit
  end
  def create
    Rails.logger.debug("video create")
    @video = Video.new(video_params)
    @video.user_id = current_user.id
    # thumbnail root_url
    urlname = @video.video_url.gsub(/http(?:s?):\/\/(?:www\.)?youtu(?:be\.com\/embed\/)/,'\1')
    Rails.logger.debug("#{urlname}")
    @video.thumbnail_url = "http://img.youtube.com/vi/" + urlname + "/default.jpg"
    respond_to do |format|
      if @video.save!
        Rails.logger.debug("video save")
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render :show, status: :created, location: @video }
      else
        Rails.logger.debug("video error")
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end
  # Likes video, increment likes count
  def like
    @video.like!
  end
  # Dislikes video, increment likes count
  def dislike
    @video.dislike!
  end
  private
  def set_video
    Rails.logger.debug(params[:id])
    if params[:id].to_i.to_s == params[:id]
      @video = Video.find(params[:id])
    else
      params[:id] = "1"
      Rails.logger.debug("video nil")
    end
  end
  def video_params
    params.require(:video).permit(:video_url, :name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.haml
!!!
%html
  %head
    %title VideoShare
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = stylesheet_link_tag    '//vjs.zencdn.net/5.0.2/video-js.css'
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = javascript_include_tag '//cdn.pubnub.com/pubnub-dev.js'
    = csrf_meta_tags
  %body{'data-no-turbolink': true}
    - if current_user
      .navbar.navbar-default.navbar-fixed-top
        .container
          .navbar-header
            = link_to 'VideoShare', root_url, class: 'navbar-brand'
          %ul.nav.navbar-nav.navbar-right
            %li
              = link_to 'Browse videos', videos_path
            %li
              = link_to 'Upload video', new_video_path
            %li.dropdown
              %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
                = current_user.email
                %span.caret
              %ul.dropdown-menu
                %li
                  = link_to 'Profile', current_user
                %li
                  = link_to 'Edit profile', edit_user_path(current_user)
                %li.divider{:role => "separator"}
                %li
                  = link_to 'Log out', destroy_user_session_path, :method => :delete
            %li#user-notifications.dropdown{"data-pn-auth-key": current_user.pn_auth_key, "data-pn-notification-channel": current_user.notification_channel}
              %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
                %span.glyphicon.glyphicon-bell
              %ul.dropdown-menu
    = yield

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VideoShare</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag    '//vjs.zencdn.net/5.0.2/video-js.css' %>
    <%= javascript_include_tag '//cdn.pubnub.com/pubnub-dev.js' %>
    <%= csrf_meta_tags %>
  </head>

  <body data-no-turbolink="true">
    <% if current_user %>
      <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
          <div class="navbar-header">
            <%= link_to 'VideoShare', root_url, class: 'navbar-brand' %>
          </div>
          <ul class="nav navbar-nav navbar-right">
            <li>
              <%= link_to 'Browse videos', videos_path %>
            </li>
            <li>
              <%= link_to 'Upload video', new_video_path %>
            </li>
	           <li class="dropdown">
             <% if user_signed_in? %>
               <%= link_to 'Log out', destroy_user_session_path, :method => :get %>
             <% else %>
               <%= link_to 'Login', new_user_session_path %>
            <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% end %>
    <% if notice %>
<p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
    <%= yield %>
  </body>
</html>

app/views/layouts/devise.haml
!!!
%html
  %head
    %title VideoShare
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body{'data-no-turbolink'= true}
    .container
      .row
        .col-md-4.col-md-offset-4
          %h1.text-center VideoShare
          = yield

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VideoShare</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body data-no-turbolink="true">
    <div class="container">
      <div class="row">
        <div class="col-md-4 col-md-offset-4">
          <h1 class="text-center">VideoShare</h1>
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/users/edit.haml
.container
  .row
    .col-md-6.col-sm-12
      %h2 Edit profile
      = simple_form_for @user do |f|
        = f.input :email
        = f.button :submit, class: 'btn-primary', value: 'Update Profile'

app/views/users/show.haml
.container
  .row
    .col-md-12
      %h2= @user.email
.container
  .row
    - @user.videos.each do |video|
      .col-md-3.thumb.video-thumb{ 'data-video-id': video.id }
        .likes
          %span.likes-count= video.likes
          %span.glyphicon.glyphicon-heart
        = link_to video, class: 'thumbnail' do
          = image_tag video.thumbnail.url(:medium_nr)

app/views/videos/index.haml
.container
  .row
    - @videos.each do |video|
      .col-md-3.thumb.video-thumb{ 'data-video-id': video.id }
        .likes
          %span.likes-count= video.likes
          %span.glyphicon.glyphicon-heart
      
  .row
    .col-md-12
      .pull-right
        = link_to 'Upload new video', new_video_url, class: 'btn btn-primary'

app/views/videos/index.html.erb
<div class="container">
  <div class="row">
    <% @videos.each do |video| %>
      <div class="col-md-3 thumb video-thumb" data-video-id="<%= video.id %>">
        <div class="likes">
          <span class="likes-count">
            <%= video.likes %>
          </span>
          <span class="glyphicon glyphicon-heart"></span>
          <span class="likes-count">
            <img src="<%= video.thumbnail_url %>">"
          </span>
          <%= link_to 'Play', video %>
        </div>
      </div>
    <% end %>
  </div>
  <div class="row">
    <div class="col-md-12">
      <div class="pull-right">
        <%= link_to 'Upload new video', new_video_url, class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
</div>

app/views/videos/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-sm-12">
      <h2>Share new video</h2>
      <%= simple_form_for @video, html: { multipart: true } do |f| %>
        <%= f.input :name %>
        <%= f.input :video_url %>
        <%= f.button :submit, class: 'btn-primary', value: 'Share Video' %>
      <% end %>
    </div>
  </div>
</div>

app/views/videos/show.html.erb
<div class="container">
  <div class="row video-full" data-video-id="<%= @video.id %>">
    <div class="col-md-10">
      <h1>
        <%= @video.name %>
      </h1>
      <p class="small">
        <%= link_to 'Back to videos' ,videos_path %>
      </p>
        <iframe height="264" id="my-video" width="640" src="<%= @video.video_url %>"
          frameborder="1" >
                </iframe>

    </div>
    <div class="col-md-2">
      <h1>
        <span class="likes-count">
          <%= @video.likes %>
        </span>
        <span class="glyphicon glyphicon-heart"></span>
      </h1>
    </div>
  </div>
</div>